# Application Settings
spring.application.name=studysync
server.port=${PORT:8081}

# Database Connection (Render PostgreSQL)
spring.datasource.url=jdbc:postgresql://dpg-d7r0aa77f7vs73cjus40-a.virginia-postgres.render.com/studysync_7bqt?sslmode=require
spring.datasource.username=studysync_7bqt_user
spring.datasource.password=bPQ8nU1CXqiHgCKWvHnrU2xz36oSTSoM
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# File Upload Limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Limit connections so the free database doesn't get overwhelmed
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000